config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  root to: "home#index"

  resources :artists
  resources :albums
  resources :wants
  resources :collections

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base


end

app/models/artist.rb
class Artist < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'pp'
  require 'dotenv'
  require 'http'

  def index

    if (params[:id_c])
      id = params[:id_c]
      password = ENV["DISCOG_TOKEN"]
      @url = params[:page_c]
      HTTP.auth("Discogs token=#{password}")
      .headers('Content-Length'=>'0').accept(:json)
      .post("https://api.discogs.com/users/drabel/collection/folders/608246/releases/#{id}")
    end

    if (params[:id_w])
      id = params[:id_w]
      password = ENV["DISCOG_TOKEN"]
      @url = params[:page_w]
      HTTP.auth("Discogs token=#{password}")
      .headers('Content-Length'=>'0').accept(:json)
      .put("https://api.discogs.com/users/drabel/wants/#{id}")
    end


    @pic = params[:pic]
    @artist = params[:artist]

    if (params[:page])
      url = params[:page]
      @pic = params[:pic]
      @artist = params[:artist]
      @passed_url = params[:page]
    elsif (@url)
      url = @url
    else
      url = params[:url]
      @passed_url = params[:url]
    end
    @pic = params[:pic]
    @artist = params[:artist]
    buffer = open(url).read
    @albums = JSON.parse(buffer)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'pp'
  require 'dotenv'
  require 'http'
  
  def index

    if params[:search]||params[:artist]||params[:title]
      require 'open-uri'
      require 'json'
      require 'pp'
        request_uri = 'https://api.discogs.com/database/search?q='
        request_query = params[:search]
        artist_query = params[:artist]
        title_query = params[:title]
        url = "#{request_uri}#{request_query}#{artist_query}#{title_query}&token=#{ENV['DISCOG_TOKEN']}"
        buffer = open(url).read
        @artists = JSON.parse(buffer)
    end

    if params[:page]
      url = params[:page]
      buffer = open(url).read
      @artists = JSON.parse(buffer)
    end

  end

  def show
    require 'open-uri'
    require 'json'
    require 'pp'
      @pic = params[:pic]
      request = params[:url]
      url = "#{request}#{ENV['DISCOG_AUTH']}"
      buffer = open(url).read
      @results = JSON.parse(buffer)
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    require 'open-uri'
    require 'json'
    require 'pp'
    pic = params[:pic]
    artist = params[:artist]
    url = "https://api.discogs.com/users/drabel/collection/folders/608246/releases?token=#{ENV['DISCOG_TOKEN']}"
      buffer = open(url).read
      @collections = JSON.parse(buffer)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/wants_controller.rb
class WantsController < ApplicationController

  def index
    require 'open-uri'
    require 'json'
    require 'pp'
    url = "https://api.discogs.com/users/drabel/wants"
    buffer = open(url).read
    @wantlist = JSON.parse(buffer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h2><%= @artist %> Releases</h2>

<br>
<br><img src="<%= @pic %>">

<% if @albums %>
  <table class="table">
    <thead>
      <th>Title</th>
      <th>Year</th>
      <th>Label</th>
      <th>Add to:</th>
      <th>Add to:</th>
    </thead>
    <tbody>
      <% @albums['releases'].each do |val| %>
        <tr>
          <td><%= val['title'] %></td>
          <td><%= val['year'] %></td>
          <td><%= val['label'] %></td>
          <td><%= link_to 'Want List', method: :put, :id_w => val['id'], :page_w => @passed_url %></td>
          <td><%= link_to 'Collection', method: :post, :id_c => val['id'], :page_c => @passed_url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="bs-example">
  <ul class="pager">
    <% if @albums['pagination']['page'] > 1 %>
      <li>&larr; <%= link_to "First", albums_path(:method => "get", :page => @albums['pagination']['urls']['first']), :pic => @pic, :artist => @artist, :class => "pager" %></li>
      <li><%= link_to "Previous", albums_path(:method => "get", :page => @albums['pagination']['urls']['prev']), :pic => @pic, :artist => @artist, :class => "pager" %></li>
    <% end%>
      |  page  <%= @albums['pagination']['page'] %>   of   <%= @albums['pagination']['pages'] %>  |
    <% if @albums['pagination']['page'] < @albums['pagination']['pages'] %>
      <li><%= link_to "Next", albums_path(:method => "get", :page => @albums['pagination']['urls']['next']), :pic => @pic, :artist => @artist, :class => "pager" %></li>
      <li><%= link_to "Last", albums_path(:method => "get", :page => @albums['pagination']['urls']['last']), :pic => @pic, :artist => @artist, :class => "pager" %> &rarr;</li>
    <% end %>
  </ul>
</div>

app/views/albums/show.html.erb
<h3>Album Show</h3>

app/views/artists/index.html.erb
<h2>Search</h2>
<br>
<div class=search-form>
  <%= form_tag(artists_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], placeholder: "Search Terms for Artists or Albums", :size => 60 %>

      <button class="btn" type="submit"><i class="icon-search">Submit</i></button>
    </div>
  <% end %>
</div>
<br>

<% if @artists %>

  <table class="table">
    <tbody>
      <% @artists['results'].in_groups_of(2, false) do |row| %>
        <tr>
          <% for artist in row %>
            <td><img src="<%= artist['thumb'] %>"></td>
            <td><%= artist['title'] %><br><%= artist['type']%><br>
              <%= link_to "More Info", artist_path(artist['title'], :url => artist['resource_url'], :pic => artist['thumb']) %><br>
              <% artist['resource_url'] %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="bs-example">
    <ul class="pager">
      <% if @artists['pagination']['page'] > 1 %>
        <li>&larr; <%= link_to "First", artists_path(:method => "get", :page => @artists['pagination']['urls']['first']), :class => "pager" %></li>
        <li><%= link_to "Prev", artists_path(:method => "get", :page => @artists['pagination']['urls']['prev']), :class => "pager" %></li>
      <% end%>
        |  page  <%= @artists['pagination']['page'] %>   of   <%= @artists['pagination']['pages'] %>  |
      <% if @artists['pagination']['page'] < @artists['pagination']['pages'] %>
        <li><%= link_to "Next", artists_path(:method => "get", :page => @artists['pagination']['urls']['next']), :class => "pager" %></li>
        <li><%= link_to "Last", artists_path(:method => "get", :page => @artists['pagination']['urls']['last']), :class => "pager" %> &rarr;</li>
      <% end %>
    </ul>
  </div>

<% end %>

app/views/artists/show.html.erb
<h3><%= @results['name'] %></h3>
<h3><%= @results['title'] %></h3>

<img src="<%= params[:pic] %>">
<br><br>

<% if @results['realname'] %>
  <h4>Real Name:</h4>
    <%= @results['realname'] %>
  <br>
<% end %>

<% if @results['profile'] && @results['profile'] != "" %>
  <h4>Profile:</h4>
    <%= @results['profile']%><br>
  <br>
<% end %>

<% if @results['year'] %>
  <h4>Release Year:</h4>
    <%= @results['year']%><br>
  <br>
<% end %>

<% if @results['releases_url'] %>
  <h4>Recordings</h4>
    <%= link_to "Releases", albums_path(:url => @results['releases_url'], :pic => params[:pic],  :artist => @results['name']) %><br>
    <br>
<% end %>

<% if @results['urls'] %>
  <h4>Related websites:</h4>
    <% @results['urls'].each do |val| %>
    <%= link_to val, val, target: "_blank" %><br>
    <% end %>
  <br>
<% end %>

<% if @results['tracklist'] %>
  <h4>Tracklist</h4>
  <table class="table">
    <tbody>
      <% @results['tracklist'].each do |val| %>
        <tr>
          <td><%= val['title'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @results['images'] %>
  <h4>Pics</h4>
  <table class="table">
    <tbody>
      <% @results['images'].each do |val| %>
        <tr>
          <td><img src="<%= val['uri'] %>"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/collections/index.html.erb
<h3>My Collection</h3>

<% if @collections %>

  <table class="table">
    <thead>
      <th>Artist</th>
      <th>Album</th>
      <th>Notes</th>

    </thead>
    <tbody>
      <% @collections['releases'].each do |val| %>
        <tr>
          <% val['basic_information']['artists'].each do |artist| %>
            <td><%= artist['name']%></td>
          <% end %>
          <td><%= val['basic_information']['title'] %></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/home/index.html.erb
<h3>Welcome to My Record Crate</h3>

<p>This is a rails app that uses the API from Discogs to display artists and album information.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= yield(:title) %></title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="bg">
    <div class="jumbotron">
      <h1>My Record Crate</h1>
      <p class="lead">+ Powered by Discogs</p>
    </div>
  </div>

  <nav class="navbar navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">My Crate</a>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Search', artists_path %></li>
          <li><%= link_to 'My Collection', collections_path %></li>
          <li><%= link_to 'Want List', wants_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user == nil && current_admin == nil%>
            <!-- <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Admin", new_admin_session_path %></li> -->
          <% end %>
          <% if current_user %>
            <li><%= link_to "Logged in as: #{current_user.email}", '/' %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <% end %>
          <% if current_admin %>
            <li><%= link_to "Logged in as: #{current_admin.email}", '/' %></li>
            <li><%= link_to "Console", 'admin_console_path' %></li>
            <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="wrapper">
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/wants/index.html.erb
<h3>Want List</h3>

<% if @wantlist %>

  <table class="table">
    <thead>
      <th>Artist</th>
      <th>Album</th>
      <th>Notes</th>

    </thead>
    <tbody>
      <% @wantlist['wants'].each do |val| %>
        <tr>
          <% val['basic_information']['artists'].each do |artist| %>
            <td><%= artist['name']%></td>
          <% end %>
          <td><%= val['basic_information']['title'] %></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>